# Generated by Django 2.1.3 on 2019-02-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prfs', '0002_auto_20190124_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='prf',
            name='phone_number',
            field=models.IntegerField(default='+375', verbose_name='телефон'),
        ),
    ]
