# Generated by Django 2.1.3 on 2019-02-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prfs', '0003_prf_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prf',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
