# Generated by Django 2.1.3 on 2019-01-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0015_auto_20190110_1532'),
        ('cart', '0002_auto_20190110_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(help_text='+37529-123-45-67', max_length=16, verbose_name='Телефон для связи')),
                ('email', models.EmailField(blank=True, help_text='user@mail.com', max_length=254, null=True, verbose_name='Электронная почта')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('informations', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart', verbose_name='Корзина')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.OrderStatus', verbose_name='Статус заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
