# Generated by Django 2.1.3 on 2019-01-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': ('Заказ',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
