# Generated by Django 2.1.3 on 2019-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190110_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='updated',
        ),
        migrations.AddField(
            model_name='orders',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
