# Generated by Django 2.1.3 on 2019-02-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190111_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name': ('Заказ',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
