# Generated by Django 2.1.3 on 2019-02-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190211_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('can_view_order', 'Can view order'),), 'verbose_name': ('Заказ',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
