# Generated by Django 2.1.3 on 2018-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20181203_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название жанра')),
                ('description', models.CharField(max_length=200, verbose_name='о жанре')),
            ],
        ),
    ]
