# Generated by Django 2.1.3 on 2018-12-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_auto_20181205_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
