# Generated by Django 2.1.3 on 2018-12-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20181205_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Изгатовитель', 'verbose_name_plural': 'Изгатовители'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'серия', 'verbose_name_plural': 'серии'},
        ),
    ]
