# Generated by Django 2.1.3 on 2018-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20181205_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(default=None, max_length=200, verbose_name='об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='автор'),
        ),
    ]
