# Generated by Django 2.1.3 on 2018-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20181205_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='123', max_length=50, verbose_name='автор'),
        ),
    ]
