# Generated by Django 2.1.3 on 2018-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_auto_20181205_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=200, verbose_name='об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='автор'),
        ),
    ]
