# Generated by Django 2.1.3 on 2018-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0013_auto_20181205_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='об авторе'),
        ),
    ]
