# Generated by Django 2.1.3 on 2019-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0015_auto_20190110_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'cтатус заказа', 'verbose_name_plural': 'cтатусы заказов'},
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='cтатус'),
        ),
    ]
