# Generated by Django 2.1.3 on 2018-12-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20181204_1410'),
        ('products', '0013_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.CharField(default=None, max_length=10, verbose_name='возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reference.Publisher', verbose_name='издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(default=None, verbose_name='вес, гр.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numbers_of_pages',
            field=models.PositiveIntegerField(default=None, verbose_name='количество страниц'),
        ),
    ]
