# Generated by Django 2.1.3 on 2018-12-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20181205_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='format',
            new_name='pr_format',
        ),
    ]
