# Generated by Django 2.1.3 on 2018-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20181205_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(blank=True, default=None, verbose_name='дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_published',
            field=models.DateField(blank=True, default=None, verbose_name='год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, verbose_name='дата последнего изменения карточки'),
        ),
    ]
