# Generated by Django 2.1.3 on 2018-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20181213_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=None, max_length=50, verbose_name='ISBN'),
        ),
    ]
