# Generated by Django 2.1.3 on 2018-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20181213_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата последнего изменения карточки'),
        ),
    ]
