# Generated by Django 2.1.3 on 2019-01-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20181226_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 10), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
