# Generated by Django 2.1.3 on 2019-01-11 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20190110_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 11), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
