# Generated by Django 2.1.3 on 2019-01-23 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20190111_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 23), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
