# Generated by Django 2.1.3 on 2019-01-24 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20190123_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 24), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
