# Generated by Django 2.1.3 on 2019-01-25 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20190124_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 25), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
