# Generated by Django 2.1.3 on 2019-02-11 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20190210_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2019, 2, 11), null=True, verbose_name='дата внесения в каталог'),
        ),
    ]
