# Generated by Django 2.1.3 on 2019-01-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
    ]
