# Generated by Django 2.1.3 on 2018-12-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='', verbose_name='обложка'),
        ),
    ]
