# Generated by Django 2.1.3 on 2018-12-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20181204_1410'),
        ('products', '0005_auto_20181204_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reference.Author', verbose_name='автор'),
        ),
    ]
