# Generated by Django 2.1.3 on 2018-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20181204_1410'),
        ('products', '0008_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='reference.Genre', verbose_name='жанр'),
        ),
    ]
