# Generated by Django 2.1.3 on 2018-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_published',
            field=models.DateField(default=None, verbose_name='год издания'),
        ),
    ]
