# Generated by Django 2.1.3 on 2018-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_book_date_of_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numbers_of_pages',
            field=models.IntegerField(default=None, verbose_name='количество страниц'),
        ),
    ]
