# Generated by Django 2.1.3 on 2018-12-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_auto_20181204_1410'),
        ('products', '0014_auto_20181204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reference.Manufacturer', verbose_name='изготовитель'),
        ),
    ]
